version: '3.7'

services:
  wordpress:
    build:
      context: ./tests
      args:
        WP_TAG: wordpress:${WP_TAG}
    restart: always
    ports:
      - ${WP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_SKIP_INSTALL: 'yes'
      WORDPRESS_DEBUG: 1
    volumes:
      - ./:/var/www/html/wp-content/plugins/kadence-blocks
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.7.8
    restart: always
    healthcheck: # The `wp` db should exist.
      test: mysqlshow -u root -ppassword wp
      start_period: 5s
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: password
    tmpfs:
      - /var/lib/mysql
