name: Build kadence-blocks.zip

on:
  workflow_dispatch

jobs:
  build:
    name: Generate release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --no-dev

      - name: Build plugin
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Generate zip
        uses: 10up/action-wordpress-plugin-build-zip@stable
        with:
          retention-days: 2 # Optional; defaults to 5
